import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/navbar";
import { Delius } from "next/font/google";
import Footer from "./footer/footer";

const delius = Delius({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-delius",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${delius.className}bg-[#F8EDE7]`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
